sudo: false

language: node_js
node_js:
  - 12

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - npm run test
  - npm run build

after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"
