sudo: false

language: node_js
node_js:
  - 9

branches:
  only:
    - master

before_script:
  - sed -i 's/\("buildSystem": "\)[^"]*\("\)/\1Travis-CI\2/g' src/assets/flags.json
  - sed -i 's/\("buildVariant": "\)[^"]*\("\)/\1prod\2/g' src/assets/flags.json
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - npm run test
  - npm run build

after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"